# Generated by Django 4.2.8 on 2023-12-22 02:06

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('order_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('order_name', models.CharField(default=None, max_length=255, null=True)),
                ('placed_date', models.DateTimeField(default=None, null=True)),
                ('approved_date', models.DateTimeField(default=None, null=True)),
                ('status_id', models.CharField(default=None, max_length=40, null=True)),
                ('currency_uom_id', models.CharField(default=None, max_length=40, null=True)),
                ('product_store_id', models.CharField(default=None, max_length=40, null=True)),
                ('sales_channel_enum_id', models.CharField(default=None, max_length=40, null=True)),
                ('grand_total', models.DecimalField(decimal_places=4, default=None, max_digits=24, null=True)),
                ('completed_date', models.DateTimeField(default=None, null=True)),
                ('credit_card', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=255, null=True))),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('party_type_enum_id', models.CharField(default=None, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('party_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.party')),
                ('salutation', models.CharField(default=None, max_length=255, null=True)),
                ('first_name', models.CharField(default=None, max_length=255, null=True)),
                ('middle_name', models.CharField(default=None, max_length=255, null=True)),
                ('last_name', models.CharField(default=None, max_length=255, null=True)),
                ('gender', models.CharField(default=None, max_length=1, null=True)),
                ('birth_date', models.DateField(default=None, null=True)),
                ('marital_status_enum_id', models.CharField(default=None, max_length=40, null=True)),
                ('employment_status_enum_id', models.CharField(default=None, max_length=40, null=True)),
                ('occupation', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default=None, max_length=255, null=True)),
                ('description', models.CharField(default=None, max_length=4095, null=True)),
                ('charge_shipping', models.CharField(default=None, max_length=1, null=True)),
                ('returnable', models.CharField(default=None, max_length=1, null=True)),
                ('owner_party_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.party')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_part_seq_id', models.CharField(max_length=40)),
                ('part_name', models.CharField(default=None, max_length=255, null=True)),
                ('status_id', models.CharField(default=None, max_length=40, null=True)),
                ('vendor_party_id', models.CharField(default=None, max_length=40, null=True)),
                ('part_total', models.DecimalField(decimal_places=4, default=None, max_digits=24, null=True)),
                ('facility_id', models.CharField(default=None, max_length=40, null=True)),
                ('shipment_method_enum_id', models.CharField(default=None, max_length=40, null=True)),
                ('customer_party_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.party')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderheader')),
            ],
            options={
                'unique_together': {('order_id', 'order_part_seq_id')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_column='order_id_column', max_length=40)),
                ('order_item_seq_id', models.CharField(db_column='order_item_seq_id_column', max_length=40)),
                ('order_part_seq_id', models.CharField(db_column='order_part_seq_id_column', default=None, max_length=40, null=True)),
                ('item_description', models.CharField(default=None, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, default=None, max_digits=26, null=True)),
                ('unit_amount', models.DecimalField(decimal_places=5, default=None, max_digits=25, null=True)),
                ('item_type_enum_id', models.CharField(default=None, max_length=40, null=True)),
                ('parent_item_seq_id', models.CharField(default=None, max_length=40, null=True)),
                ('product_id', models.ForeignKey(db_column='product_id_column', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
            ],
            options={
                'db_table': 'order_item',
                'unique_together': {('order_id', 'order_item_seq_id')},
            },
        ),
    ]
