# Generated by Django 4.2.8 on 2023-12-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='organization_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='owner_party_id',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='pseudo_id',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='role_type_id',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
