# Generated by Django 4.2.8 on 2023-12-22 03:20

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization_role_remove_party_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheader',
            name='approved_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='completed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='credit_card',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default=None, max_length=255, null=True)),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='currency_uom_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='order_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='placed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='product_store_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='sales_channel_enum_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='status_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type_enum_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_part_seq_id',
            field=models.CharField(blank=True, db_column='order_part_seq_id_column', default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='parent_item_seq_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id_column', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=26, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_amount',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='customer_party_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.party'),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='facility_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='part_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='part_total',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='shipment_method_enum_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='status_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='vendor_party_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization'),
        ),
        migrations.AlterField(
            model_name='party',
            name='owner_party_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_type_enum_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='pseudo_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='employment_status_enum_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='marital_status_enum_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='salutation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='charge_shipping',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=4095, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner_party_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.party'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='returnable',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
