# Generated by Django 4.2.8 on 2023-12-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_asset_class_enum_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheader',
            name='order_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
