# Generated by Django 4.2.8 on 2023-12-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_orderheader_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheader',
            name='credit_card',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
