# Generated by Django 4.2.8 on 2023-12-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_orderheader_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpart',
            name='order_part_seq_id',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
