# Generated by Django 4.2.8 on 2023-12-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_orderpart_order_part_seq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.ForeignKey(blank=True, db_column='product_id_column', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_orders', to='api.product'),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='customer_party_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_order_parts', to='api.party'),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_parts', to='api.orderheader'),
        ),
        migrations.AlterField(
            model_name='party',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_organizationn', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='party',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_role', to='api.role'),
        ),
        migrations.AlterField(
            model_name='person',
            name='party_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person', serialize=False, to='api.party'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner_party_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.party'),
        ),
    ]
