# Generated by Django 4.2.8 on 2023-12-24 07:09

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_orderheader_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheader',
            name='credit_card',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default=None, max_length=255, null=True)),
        ),
    ]
