# Generated by Django 4.2.5 on 2023-12-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_orderheader_credit_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='party',
            name='owner_party_id',
        ),
        migrations.RemoveField(
            model_name='party',
            name='pseudo_id',
        ),
        migrations.RemoveField(
            model_name='party',
            name='role',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
