# Generated by Django 4.2.5 on 2023-12-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_party_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_seq_id',
            field=models.CharField(blank=True, db_column='order_item_seq_id_column', default=None, max_length=40, null=True),
        ),
    ]
